### ISSUE TITLE
Cannot create Looker user

### ISSUE THREAD

**Issue by kylasam** [hirosassa/terraform-provider-looker#19]
Hello, I have been trying to create a Looker user with the modules provided here but running into issues as always,
`resource "looker_user" "user" {
  email = "test.user@gmil.com"
  first_name = "Reporting"
  last_name  = "API User"
}
`

and it Errors out as, `2022-04-03T06:15:12.649+0200 [ERROR] vertex "looker_user.user (expand)" error: response error: 404 Not Found
`

`│ Error: response error: 404 Not Found
│ 
│   with looker_user.user,
│   on tf_read_looker_users.tf line 27, in resource "looker_user" "user":
│   27: resource "looker_user" "user" {
│ 
`

**Comment by hirosassa** [comment]
@kylasam Thanks kylasam! Yeah, this is known issue of v4 API of Looker
Currently I'm working on supporting v4. Please wait a minutes (maybe it takes a few days).

**Comment by hirosassa** [comment]
@kylasam Sorry for keep you waiting so long. I found that the recent version of looker Go sdk contains bug.
I created PR for fixing this bug here.
https://github.com/looker-open-source/sdk-codegen/pull/1045

And after it is merged, we can also merge this PR. https://github.com/hirosassa/terraform-provider-looker/pull/20

Please wait little bit more.

**Comment by kylasam** [comment]
Thank you so much :) . Let me give a try and keep you posted and a big Kudo's for your rapt attention.

**Comment by kylasam** [comment]
Seems like an issue,
`looker_connection.snowflake_connection: Creating...
╷
│ Error: Request cancelled
│
│   with looker_connection.snowflake_connection,
│   on looker_connection.tf line 2, in resource "looker_connection" "snowflake_connection":
│    2: resource "looker_connection" "snowflake_connection" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-looker_v0.8.3 plugin:

panic: interface conversion: interface {} is int, not string

goroutine 36 [running]:
github.com/hirosassa/terraform-provider-looker/pkg/looker.expandWriteDBConnection(0xf0)
	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:329 +0x16f4
github.com/hirosassa/terraform-provider-looker/pkg/looker.resourceConnectionCreate({0x19d9a48, 0xc00020d560}, 0xc0000172d8, {0x18bfb00, 0xc0000e4f88})
	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:244 +0x89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001c3420, {0x19d9a80, 0xc00007f1a0}, 0xd, {0x18bfb00, 0xc0000e4f88})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001c3420, {0x19d9a80, 0xc00007f1a0}, 0xc000420b60, 0xc000442c80, {0x18bfb00, 0xc0000e4f88})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0x9ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003ca900, {0x19d99d8, 0xc00020efc0}, 0xc0000cb090)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003b4640, {0x19d9a80, 0xc00007e6f0}, 0xc0003a0000)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1883140, 0xc0003b4640}, {0x19d9a80, 0xc00007e6f0}, 0xc00020cc00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017ee00, {0x19e9c98, 0xc000474000}, 0xc0000ce120, 0xc0003c5f50, 0x1f30d20, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00017ee00, {0x19e9c98, 0xc000474000}, 0xc0000ce120, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-looker_v0.8.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`

**Comment by hirosassa** [comment]
@kylasam Sorry, this problem fixed in https://github.com/hirosassa/terraform-provider-looker/pull/22/files

Please use latest provider.
https://registry.terraform.io/providers/hirosassa/looker/0.8.5?pollNotifications=true

**Comment by hirosassa** [comment]
@yu-iskw Thanks for the report! It looks related issue. Recently Looker API v4 GA-ed with breaking change of API client.
I'll take a look shortly.
Please wait a moment.

**Comment by yu-iskw** [comment]
FYI: When I used the Looker SDK in python rather than the provider, I was able to create groups and roles. As you may think, there is something wrong with the endpoint and request behind the provider.

**Comment by hirosassa** [comment]
@yu-iskw @kylasam This problems are fixed in https://github.com/hirosassa/terraform-provider-looker/pull/27.
Please try v0.8.6
