### ISSUE TITLE
The provider plugin crashes when using the `pdt_context_override` block

### ISSUE THREAD

**Issue by jbennett7** [hirosassa/terraform-provider-looker#49]
When trying to use `pdt_context_override` the provider plugin crashes with

`panic: interface conversion: interface {} is string, not *string`

Full error:
```
  # looker_connection.tf_example_pdt_context will be created
  + resource "looker_connection" "tf_example_pdt_context" {
      + database               = “DATABASE”
      + db_timezone            = "UTC"
      + dialect_name           = "databricks"
      + host                   = “HOST”
      + id                     = (known after apply)
      + jdbc_additional_params = “STRING”
      + name                   = "tf_example_jdbc"
      + password               = (sensitive value)
      + pdt_concurrency        = 1
      + pool_timeout           = 120
      + port                   = "443"
      + ssl                    = true
      + username               = “USER”

      + pdt_context_override {
          + after_connect_statements = "after_connect_statments"
          + database                 = “DATABASE”
          + file_type                = "text"
          + host                     = “HOST”
          + port                     = "443"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
2023-10-03T11:24:47.700-0400 [INFO]  provider: configuring client automatic mTLS
2023-10-03T11:24:47.702-0400 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hirosassa/looker/0.8.9/darwin_arm64/terraform-provider-looker_v0.8.9 args=[.terraform/providers/registry.terraform.io/hirosassa/looker/0.8.9/darwin_arm64/terraform-provider-looker_v0.8.9]
2023-10-03T11:24:47.704-0400 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hirosassa/looker/0.8.9/darwin_arm64/terraform-provider-looker_v0.8.9 pid=67726
2023-10-03T11:24:47.704-0400 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hirosassa/looker/0.8.9/darwin_arm64/terraform-provider-looker_v0.8.9
2023-10-03T11:24:47.712-0400 [INFO]  provider.terraform-provider-looker_v0.8.9: configuring server automatic mTLS: timestamp=2023-10-03T11:24:47.712-0400
2023-10-03T11:24:47.721-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: plugin address: address=/var/folders/4s/q6n0xzs97w55ms7_yd77ln8r0000gp/T/plugin3708604435 network=unix timestamp=2023-10-03T11:24:47.721-0400
2023-10-03T11:24:47.721-0400 [DEBUG] provider: using plugin: version=5
looker_connection.tf_example_pdt_context: Creating...
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: panic: interface conversion: interface {} is string, not *string
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9:
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: goroutine 43 [running]:
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hirosassa/terraform-provider-looker/pkg/looker.expandWriteDBConnection(0x140000ce2d0?)
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:428 +0x153c
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hirosassa/terraform-provider-looker/pkg/looker.resourceConnectionCreate({0x101611ce8, 0x14000083920}, 0x0?, {0x101603960?, 0x14000288518?})
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:241 +0x5c
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400022f420, {0x101611d20, 0x140000db0b0}, 0xd?, {0x101603960, 0x14000288518})
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0xe8
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400022f420, {0x101611d20, 0x140000db0b0}, 0x140004b1930, 0x14000481b80, {0x101603960, 0x14000288518})
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0x714
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400042c390, {0x101611c78?, 0x140000e0380?}, 0x140000e8140)
2023-10-03T11:24:47.734-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xb70
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400038c6e0, {0x101611d20?, 0x140000da810?}, 0x140003791f0)
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x384
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1015c5e80?, 0x1400038c6e0}, {0x101611d20, 0x140000da810}, 0x14000083200, 0x0)
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: google.golang.org/grpc.(*Server).processUnaryRPC(0x140001fce00, {0x101615678, 0x1400048a1a0}, 0x140001ddc20, 0x14000442060, 0x101af0f40, 0x0)
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	google.golang.org/grpc@v1.45.0/server.go:1282 +0xb28
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: google.golang.org/grpc.(*Server).handleStream(0x140001fce00, {0x101615678, 0x1400048a1a0}, 0x140001ddc20, 0x0)
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	google.golang.org/grpc@v1.45.0/server.go:1619 +0x82c
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	google.golang.org/grpc@v1.45.0/server.go:921 +0x84
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-10-03T11:24:47.735-0400 [DEBUG] provider.terraform-provider-looker_v0.8.9: 	google.golang.org/grpc@v1.45.0/server.go:919 +0x290
2023-10-03T11:24:47.735-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hirosassa/looker/0.8.9/darwin_arm64/terraform-provider-looker_v0.8.9 pid=67726 error="exit status 2"
2023-10-03T11:24:47.735-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
╷
│ Error: Plugin did not respond
│
│   with looker_connection.tf_example_pdt_context,
│   on connections.tf line 16, in resource "looker_connection" "tf_example_pdt_context":
│   16: resource "looker_connection" "tf_example_pdt_context" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-looker_v0.8.9 plugin:

panic: interface conversion: interface {} is string, not *string

goroutine 43 [running]:
github.com/hirosassa/terraform-provider-looker/pkg/looker.expandWriteDBConnection(0x140000ce2d0?)
	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:428 +0x153c
github.com/hirosassa/terraform-provider-looker/pkg/looker.resourceConnectionCreate({0x101611ce8, 0x14000083920}, 0x0?, {0x101603960?, 0x14000288518?})
	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:241 +0x5c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400022f420, {0x101611d20, 0x140000db0b0}, 0xd?, {0x101603960, 0x14000288518})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400022f420, {0x101611d20, 0x140000db0b0}, 0x140004b1930, 0x14000481b80, {0x101603960, 0x14000288518})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0x714
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400042c390, {0x101611c78?, 0x140000e0380?}, 0x140000e8140)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400038c6e0, {0x101611d20?, 0x140000da810?}, 0x140003791f0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x384
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1015c5e80?, 0x1400038c6e0}, {0x101611d20, 0x140000da810}, 0x14000083200, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001fce00, {0x101615678, 0x1400048a1a0}, 0x140001ddc20, 0x14000442060, 0x101af0f40, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xb28
google.golang.org/grpc.(*Server).handleStream(0x140001fce00, {0x101615678, 0x1400048a1a0}, 0x140001ddc20, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x290

Error: The terraform-provider-looker_v0.8.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-10-03T11:24:47.745-0400 [DEBUG] provider: plugin exited
```

**Comment by Nabil-Lahssini** [comment]
https://registry.terraform.io/providers/devoteamgcloud/looker/latest Works on this provider
