### ISSUE TITLE
Failing to import looker connection 

### ISSUE THREAD

**Issue by dastanko** [hirosassa/terraform-provider-looker#9]
Hello, there. Would be glad if someone will be able to help. I'm having issues with importing existing looker connections.

### Steps to reproduce
* terraform import looker_connection.snowflake_audit snowflake_audit

### Trace logs 
`
2021/10/28 08:29:30 [TRACE] vertex "looker_connection.snowflake_audit (import id \"snowflake_audit\")": expanding dynamic subgraph
2021/10/28 08:29:30 [TRACE] vertex "looker_connection.snowflake_audit (import id \"snowflake_audit\")": entering dynamic subgraph
2021/10/28 08:29:30 [TRACE] dag/walk: visiting "import looker_connection.snowflake_audit result"
2021/10/28 08:29:30 [TRACE] vertex "import looker_connection.snowflake_audit result": starting visit (*terraform.graphNodeImportStateSub)
2021/10/28 08:29:30 [TRACE] GRPCProvider: ReadResource
2021-10-28T08:29:32.362Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: panic: runtime error: invalid memory address or nil pointer dereference
2021-10-28T08:29:32.364Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb36a38]
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: goroutine 14 [running]:
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hirosassa/terraform-provider-looker/pkg/looker.flattenConnection(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:517 +0x678
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hirosassa/terraform-provider-looker/pkg/looker.resourceConnectionRead(0xdec108, 0xc00009d200, 0xc000162e80, 0xcefd80, 0xc00030c568, 0xc0000a18e0, 0xc000175908, 0x40e0f8)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_connection.go:271 +0x308
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000312c40, 0xdec098, 0xc000302fc0, 0xc000162e80, 0xcefd80, 0xc00030c568, 0x0, 0x0, 0x0)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000312c40, 0xdec098, 0xc000302fc0, 0xc000334a80, 0xcefd80, 0xc00030c568, 0xc0000a2688, 0x0, 0x0, 0x0)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000300780, 0xdec098, 0xc000302fc0, 0xc000303000, 0xc000302fc0, 0x40b965, 0xc7c9e0)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0000c33e0, 0xdec140, 0xc000302fc0, 0xc00009cd80, 0xc0000c33e0, 0xc00018c5d0, 0xc0002b4ba0)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xcaeb60, 0xc0000c33e0, 0xdec140, 0xc00018c5d0, 0xc00009cd20, 0x0, 0xdec140, 0xc00018c5d0, 0xc00019c6c0, 0x226)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032a540, 0xdf39d8, 0xc000527380, 0xc0002a4300, 0xc00009e5a0, 0x121cad0, 0x0, 0x0, 0x0)
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2021-10-28T08:29:32.365Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: google.golang.org/grpc.(*Server).handleStream(0xc00032a540, 0xdf39d8, 0xc000527380, 0xc0002a4300, 0x0)
2021-10-28T08:29:32.366Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2021-10-28T08:29:32.366Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00037e040, 0xc00032a540, 0xdf39d8, 0xc000527380, 0xc0002a4300)
2021-10-28T08:29:32.366Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2021-10-28T08:29:32.366Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-10-28T08:29:32.366Z [DEBUG] plugin.terraform-provider-looker_v0.5.0: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021-10-28T08:29:32.369Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-10-28T08:29:32.370Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hirosassa/looker/0.5.0/linux_amd64/terraform-provider-looker_v0.5.0 pid=1428 error="exit status 2"
2021/10/28 08:29:32 [TRACE] vertex "import looker_connection.snowflake_audit result": visit complete
2021/10/28 08:29:32 [TRACE] vertex "looker_connection.snowflake_audit (import id \"snowflake_audit\")": dynamic subgraph encountered errors
2021/10/28 08:29:32 [TRACE] vertex "looker_connection.snowflake_audit (import id \"snowflake_audit\")": visit complete
2021/10/28 08:29:32 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hirosassa/looker\"] (close)" errored, so skipping
2021/10/28 08:29:32 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/10/28 08:29:32 [DEBUG] DELETE https://gitlab.com/api/v4/projects/29931685/terraform/state/terraform-looker-permissions-dev/lock
2
`

Looks like the problem is in https://github.com/hirosassa/terraform-provider-looker/blob/master/pkg/looker/resource_connection.go#L517. Where it tries to get `user_attribute_fields`, but it's failing to read that part.

**Comment by hirosassa** [comment]
@dastanko Sorry for late reply. I think it fixed but I don't have snowflake environment to try. 
Cloud you please check this by using `v0.7.1` on your environment.

**Comment by hirosassa** [comment]
This issue looks solved. Close.
